Ext.define('mobapp.view.Rss',{
	extend:'Ext.Panel',
	xtype:'rss',
	config:{
		scrollable:true,
		title:'RSS',
		iconCls:'search',
		items:[
			{
				xtype:'titlebar',
				docked:'top',
				title:'RSS'
			},
			{
				xtype:'fieldset',
				title:'get RSS data',
				items:[
					{
						xtype:'textfield',
						label:'RSS:',
						name:'rss'
					},
					{
						xtype:'button',
						text:'search and get',
						ui:'action',
						handler:function(){
							var url = document.getElementsByName('rss')[0].value;
							if(url != '')
							{
								alert(url);
							}
							else
							{
								alert('RSS field is EMPTY!');
							}
						}
					},
					{
						xtype:"fieldset",
						title:"form",
						items:[
							{
								xtype:"textfield",
								label:"Name:",
								name:'name'
							},
							{
								xtype:"textfield",
								name:"email",
								label:"E-mail"
							},
							{
								xtype:"textareafield",
								label:"Massage",
								name:"massage"
							},
							{
								xtype:"radiofield",
								label:"Male",
								name:"male",
								value:1,
								checked:true
							},
							{
								xtype:"radiofield",
								label:"Female",
								name:"male",
								value:0
							},
							{
								xtype:"checkboxfield",
								label:"Mersedes",
								name:"car",
								checked:true,
								value:1
							},
							{
								xtype:"checkboxfield",
								label:"Cooper",
								name:"car2",
								value:2
							},
							{
								xtype:"checkboxfield",
								label:"BMW",
								name:"car3",
								value:3
							},
							{
								xtype:"selectfield",
								label:"Amis:",
								options:[
									{
										text:"hunvar",
										value:0
									},
									{
										text:"petrvar",
										value:1
									},
									{
										text:"mart",
										value:2
									},
									{
										text:"april",
										value:3
									},
									{
										text:"mayis",
										value:4
									},
									{
										text:"hunis",
										value:5,
										checked:true
									},
									{
										text:"hulis",
										value:6
									},
									{
										text:"ogostos",
										value:7
									},
									{
										text:"september",
										value:8
									},
									{
										text:"hoktember",
										value:9
									},
									{
										text:"noyember",
										value:10
									},
									{
										text:"dektember",
										value:11
									}
								]
							},
							{
								xtype:"button",
								text:"Send",
								handler:function(){
									alert("Clicked");
								}
							}
						]
					}
				]
			}
		]	
	}
});